version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - graylog
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - graylog

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    depends_on:
      opensearch:
        condition: service_healthy
      mongodb:
        condition: service_started
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_OPENSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_SERVER_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9000:9000"       # Web UI
      - "1514:1514"       # Syslog TCP
      - "1514:1514/udp"   # Syslog UDP
      - "12201:12201"     # GELF TCP
      - "12201:12201/udp" # GELF UDP
    networks:
      - graylog
    volumes:
      - graylog_data:/usr/share/graylog/data

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    depends_on:
      - graylog
    environment:
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - DOMAIN=${VAULTWARDEN_DOMAIN}
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED}
      - LOG_LEVEL=${VAULTWARDEN_LOG_LEVEL}
    volumes:
      - vaultwarden_data:/data
    ports:
      - "8080:80"
    logging:
      driver: gelf
      options:
        gelf-address: udp://graylog:12201
        tag: "vaultwarden"
    networks:
      - graylog

volumes:
  opensearch_data:
  mongodb_data:
  graylog_data:
  vaultwarden_data:

networks:
  graylog:
